/** Ribbon Modernism: Cloudflare v2 R2 asset URLs generated by the authenticated deployment publisher. */
export const cloudflareAssets = {
  "heroRitual": "https://api-v2.rinovabd.com/api/media/site%2Fv2%2Fhero-ritual.png",
  "productEssentials": "https://api-v2.rinovabd.com/api/media/site%2Fv2%2Fproduct-essentials.png",
  "collectionFace": "https://api-v2.rinovabd.com/api/media/site%2Fv2%2Fcollection-face.png",
  "adminStilllife": "https://api-v2.rinovabd.com/api/media/site%2Fv2%2Fadmin-stilllife.png",
  "ribbonLoopSymbol": "https://api-v2.rinovabd.com/api/media/site%2Fv2%2Fribbon-loop-symbol.png",
  "shopEditorialRibbon": "https://api-v2.rinovabd.com/api/media/site%2Fv2%2Fshop-editorial-ribbon.png",
  "shopBeautyCrop": "https://api-v2.rinovabd.com/api/media/site%2Fv2%2Fshop-beauty-crop.png"
} as const;
