/** Ribbon Modernism customer account: a quiet, purpose-built entry point for secure registration and sign-in. */
import { ArrowRight, CircleAlert, LogOut } from "lucide-react";
import { useState, type FormEvent } from "react";
import { StoreHeader } from "@/components/StoreHeader";
import { useAuth } from "@/contexts/AuthContext";

export default function Account() {
  const { user, ready, signIn, register, signOut } = useAuth(); const [mode, setMode] = useState<"signin" | "register">("signin"); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); setError(""); try { if (mode === "signin") await signIn(email, password); else await register(name, email, password); } catch (cause) { setError(cause instanceof Error ? cause.message : "We could not complete that request."); } finally { setSaving(false); } };
  return <div className="site-shell commerce-page"><StoreHeader /><main className="account-layout"><section className="account-intro"><div className="account-ribbon-rail"><span>Account desk</span><i /><span>Private by design</span><i /><span>V2 secure</span></div><span className="eyebrow">Rinovabd account</span><h1>Keep your rituals<br /><em>close at hand.</em></h1><p>Sign in to see purchases, keep delivery details at hand, and use protected order links with confidence.</p><a href="/shop" className="text-action text-action--dark">Continue the edit <ArrowRight size={17} /></a></section><section className="account-card"><div className="account-ticket"><span>Account counter</span><span>Rinovabd / 02</span></div>{!ready ? <p>Checking your session…</p> : user ? <div className="account-signed"><span className="eyebrow">Signed in</span><h2>Hello, <em>{user.name}.</em></h2><p>{user.email}</p><a className="button button--pink" href="/cart">Open your bag <ArrowRight size={17} /></a><button className="button button--outline" onClick={() => signOut()}><LogOut size={16} />Sign out</button></div> : <><div className="account-switch"><button className={mode === "signin" ? "active" : ""} onClick={() => setMode("signin")}>Sign in</button><button className={mode === "register" ? "active" : ""} onClick={() => setMode("register")}>Create account</button></div><form className="account-form" onSubmit={submit}>{mode === "register" && <label>Name<input required value={name} onChange={(event) => setName(event.target.value)} placeholder="Your name" /></label>}<label>Email<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@example.com" /></label><label>Password<input required type="password" minLength={8} value={password} onChange={(event) => setPassword(event.target.value)} placeholder="At least 8 characters" /></label><button className="button button--ink" disabled={saving}>{saving ? "One moment" : mode === "signin" ? "Sign in" : "Create account"}<ArrowRight size={17} /></button>{error && <p className="form-error"><CircleAlert size={16} />{error}</p>}</form></>}</section></main></div>;
}
