/** Ribbon Modernism: this studio dashboard turns operations into a tactile production desk, with clear data and restrained pink signals. */
import { ArrowUpRight, Check, ChevronDown, CircleAlert, CloudUpload, Ellipsis, Eye, ImagePlus, MoreHorizontal, Plus, Search, Sparkles, Upload, X } from "lucide-react";
import { useEffect, useMemo, useState, type ChangeEvent, type FormEvent } from "react";
import { AdminSidebar, type AdminView } from "@/components/AdminSidebar";
import { formatBDT, productSeed, type Product, type ProductStatus } from "@/lib/catalog";
import { API_BASE, adminLogin, fetchAdminProducts, saveAdminProduct, uploadMedia } from "@/lib/api";

type MediaItem = { id: string; name: string; type: string; url: string; uploaded: string };
const initialMedia: MediaItem[] = [
  { id: "media-hero", name: "hero-ritual.png", type: "Campaign image", url: "/manus-storage/rinovabd-hero-ritual_f76d3417.png", uploaded: "Today" },
  { id: "media-essentials", name: "pink-essentials.png", type: "Product image", url: "/manus-storage/rinovabd-product-pink-essentials_5fd5096d.png", uploaded: "Today" },
  { id: "media-face", name: "collection-face.png", type: "Editorial image", url: "/manus-storage/rinovabd-collection-face_bcb32ab5.png", uploaded: "Today" },
];

export default function Admin() {
  const [session, setSession] = useState(() => window.sessionStorage.getItem("rinovabd-v2-admin-session") || "");
  const [view, setView] = useState<AdminView>("overview");
  const [products, setProducts] = useState<Product[]>(productSeed);
  const [media, setMedia] = useState<MediaItem[]>(initialMedia);
  const [search, setSearch] = useState("");
  const [modalOpen, setModalOpen] = useState(false);
  const [editing, setEditing] = useState<Product | null>(null);
  const [toast, setToast] = useState("");

  const filteredProducts = useMemo(() => products.filter((product) => `${product.name} ${product.category} ${product.id}`.toLowerCase().includes(search.toLowerCase())), [products, search]);
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 3200); };
  useEffect(() => { if (session) fetchAdminProducts(session).then(setProducts).catch((cause: Error) => notify(cause.message)); }, [session]);
  const onUpload = async (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;
    event.target.value = "";
    try {
      const uploaded = await uploadMedia(session, file);
      setMedia((current) => [{ id: uploaded.asset.id, name: file.name, type: uploaded.asset.type, url: `${API_BASE}${uploaded.asset.url}`, uploaded: "Just now" }, ...current]);
      notify("Image is now in the new isolated v2 media library.");
    } catch (cause) { notify(cause instanceof Error ? cause.message : "Image upload could not be completed."); }
  };
  const saveProduct = async (product: Product) => {
    try {
      const saved = await saveAdminProduct(session, product, Boolean(editing));
      setProducts((current) => editing ? current.map((item) => item.id === saved.id ? saved : item) : [saved, ...current]);
      setModalOpen(false); setEditing(null); notify(editing ? "Product is published to the new v2 catalogue." : "New product added to the new v2 catalogue.");
    } catch (cause) { notify(cause instanceof Error ? cause.message : "Product could not be saved."); }
  };

  if (!session) return <AdminGate onAuthorized={(nextSession) => { window.sessionStorage.setItem("rinovabd-v2-admin-session", nextSession); setSession(nextSession); }} />;

  const content = view === "overview" ? <Overview products={products} onViewProducts={() => setView("catalogue")} />
    : view === "catalogue" ? <Catalogue products={filteredProducts} search={search} setSearch={setSearch} onCreate={() => { setEditing(null); setModalOpen(true); }} onEdit={(product) => { setEditing(product); setModalOpen(true); }} />
    : view === "media" ? <MediaDesk media={media} onUpload={onUpload} />
    : <WorkspacePlaceholder view={view} onNavigate={setView} />;

  return <div className="admin-shell"><AdminSidebar active={view} onChange={setView} /><main className="admin-main"><header className="admin-topbar"><div><span className="eyebrow">Rinovabd / studio</span><h1>{view === "overview" ? "Good afternoon, Nabila." : view === "catalogue" ? "Product library" : view === "media" ? "Media desk" : view === "content" ? "Site content" : view === "orders" ? "Orders" : "Studio settings"}</h1></div><div className="admin-top-actions"><div className="live-status"><span />Storefront live</div><button className="admin-avatar">NB</button></div></header>{content}</main>{modalOpen && <ProductModal product={editing} media={media} onClose={() => { setModalOpen(false); setEditing(null); }} onSave={saveProduct} />}{toast && <div className="admin-toast"><Check size={18} />{toast}</div>}</div>;
}

function AdminGate({ onAuthorized }: { onAuthorized: (session: string) => void }) {
  const [token, setToken] = useState(""); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSubmitting(true); setError(""); try { const result = await adminLogin(token); onAuthorized(result.session); } catch (cause) { setError(cause instanceof Error ? cause.message : "Studio sign-in failed."); } finally { setSubmitting(false); } };
  return <main className="admin-gate"><section><img src="/manus-storage/rinovabd-ribbon-loop-symbol_75291c2e.png" alt="" /><div className="gate-command-rail"><span>Studio desk</span><i /><span>V2 secure</span><i /><span>Product ops</span></div><span className="eyebrow">Rinovabd / private studio</span><h1>The studio is<br /><em>for the people<br />making the edit.</em></h1><p>Enter the access token for the newly deployed v2 Worker. Your session expires automatically after twelve hours.</p><form onSubmit={submit}><label htmlFor="studio-token">Studio access token</label><input id="studio-token" type="password" value={token} onChange={(event) => setToken(event.target.value)} required placeholder="Paste the v2 token" /><button className="button button--pink" disabled={submitting}>{submitting ? "Checking access" : "Open studio desk"}<ArrowUpRight size={17} /></button>{error && <div className="gate-error"><CircleAlert size={16} />{error}</div>}</form><a href="/">Return to storefront</a></section><div><img src="/manus-storage/rinovabd-admin-stilllife_dd7b6ad1.png" alt="Rinovabd studio work surface" /></div></main>;
}

function Overview({ products, onViewProducts }: { products: Product[]; onViewProducts: () => void }) {
  const lowStock = products.filter((product) => product.stock < 10).length;
  return <div className="admin-content"><section className="studio-hero"><div><span className="eyebrow">Tuesday, August 28</span><h2>Today’s edit is <em>ready to move.</em></h2><p>Keep your launch crisp: two small tasks deserve your attention before noon.</p><button onClick={onViewProducts}>Review product library <ArrowUpRight size={17} /></button></div><img src="/manus-storage/rinovabd-admin-stilllife_dd7b6ad1.png" alt="Rinovabd studio product arrangement" /></section><section className="metrics-grid"><Metric label="Sales, this month" value="৳86,420" trend="+12.8%" tone="pink" /><Metric label="Orders to pack" value="14" trend="4 priority" tone="ink" /><Metric label="Product units" value={String(products.reduce((sum, product) => sum + product.stock, 0))} trend={`${lowStock} low stock`} tone="paper" /><Metric label="Launch list" value="03" trend="Next drop Fri" tone="paper" /></section><section className="admin-two-col"><div className="production-card"><div className="card-heading"><div><span className="eyebrow">Operations</span><h3>Production queue</h3></div><button className="quiet-icon" aria-label="Queue options"><MoreHorizontal size={20} /></button></div><div className="queue-list"><QueueItem number="01" title="Review Cloud Melt stock" detail="8 units are below the preferred shelf level" status="Needs review" /><QueueItem number="02" title="Schedule September edit" detail="The homepage ribbon is ready for a campaign handoff" status="Draft" /><QueueItem number="03" title="Publish ingredient note" detail="Final copy received from the product desk" status="Ready" /></div></div><div className="insight-card"><span className="eyebrow">Studio signal</span><h3>Your most visited<br />category is <em>skin ritual.</em></h3><div className="signal-bars">{[46, 72, 58, 88, 64, 92, 70].map((height, index) => <i key={index} style={{ height: `${height}%` }} />)}</div><p>Last 7 days · storefront interest</p></div></section><section className="admin-table-card"><div className="card-heading"><div><span className="eyebrow">Last 24 hours</span><h3>Recent orders</h3></div><button className="quiet-link">View all <ArrowUpRight size={16} /></button></div><table><thead><tr><th>Order</th><th>Customer</th><th>Items</th><th>Status</th><th>Total</th></tr></thead><tbody><tr><td>#RV-1042</td><td>Fahmida R.</td><td>2 pieces</td><td><span className="status status--ready">Ready to pack</span></td><td>৳2,580</td></tr><tr><td>#RV-1041</td><td>Naima S.</td><td>1 piece</td><td><span className="status status--moving">In delivery</span></td><td>৳1,690</td></tr><tr><td>#RV-1040</td><td>Akib H.</td><td>3 pieces</td><td><span className="status status--complete">Delivered</span></td><td>৳3,970</td></tr></tbody></table></section></div>;
}

function Metric({ label, value, trend, tone }: { label: string; value: string; trend: string; tone: "pink" | "ink" | "paper" }) { return <article className={`metric-card metric-card--${tone}`}><span>{label}</span><strong>{value}</strong><p>{trend}</p></article>; }
function QueueItem({ number, title, detail, status }: { number: string; title: string; detail: string; status: string }) { return <div className="queue-item"><span>{number}</span><div><h4>{title}</h4><p>{detail}</p></div><em>{status}</em></div>; }

function Catalogue({ products, search, setSearch, onCreate, onEdit }: { products: Product[]; search: string; setSearch: (value: string) => void; onCreate: () => void; onEdit: (product: Product) => void }) { return <div className="admin-content"><section className="catalogue-controls"><div className="admin-search"><Search size={18} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search name, category, or SKU" /></div><button className="button button--pink button--small" onClick={onCreate}><Plus size={17} />New product</button></section><section className="catalogue-statbar"><span><strong>{products.length}</strong> products shown</span><span><CircleAlert size={16} /> Stock position updates after publish</span><button><Ellipsis size={19} /></button></section><section className="product-admin-table">{products.map((product) => <article key={product.id}><div className="admin-product-preview"><img src={product.image} alt="" /><div><span>{product.id.toUpperCase()}</span><h3>{product.name}</h3><p>{product.category} · {product.shade}</p></div></div><div><span className={`stock-meter ${product.stock < 10 ? "stock-meter--low" : ""}`}>{product.stock} in stock</span></div><strong>{formatBDT(product.price)}</strong><span className={`status ${product.status === "Low stock" ? "status--warning" : "status--ready"}`}>{product.status}</span><button className="edit-product" onClick={() => onEdit(product)}>Edit <ArrowUpRight size={16} /></button></article>)}</section></div>; }

function MediaDesk({ media, onUpload }: { media: MediaItem[]; onUpload: (event: ChangeEvent<HTMLInputElement>) => void }) { return <div className="admin-content"><section className="media-intro"><div><span className="eyebrow">Upload & organise</span><h2>One shelf for every<br /><em>visual decision.</em></h2></div><label className="button button--pink button--small"> <Upload size={17} />Upload image<input type="file" accept="image/*" onChange={onUpload} hidden /></label></section><label className="dropzone"><CloudUpload size={30} /><strong>Drop campaign or product images here</strong><span>PNG, JPG or WebP · Publish sends files to the new isolated media library.</span><input type="file" accept="image/*" onChange={onUpload} hidden /></label><section className="media-grid">{media.map((item) => <article key={item.id}><img src={item.url} alt="" /><div><span>{item.type}</span><h3>{item.name}</h3><p>{item.uploaded}</p></div><button aria-label={`View ${item.name}`}><Eye size={17} /></button></article>)}</section></div>; }

function WorkspacePlaceholder({ view, onNavigate }: { view: AdminView; onNavigate: (view: AdminView) => void }) { const title = view === "content" ? "Shape the next storefront moment." : view === "orders" ? "A focused lane for every delivery." : "Keep the studio recognisably yours."; return <div className="admin-content"><section className="placeholder-panel"><Sparkles size={28} /><span className="eyebrow">New studio module</span><h2>{title}</h2><p>This redesigned workspace has the structure for this production module. Connect the new Worker deployment to publish, process, and retain its records separately from the previous environment.</p><div><button className="button button--ink" onClick={() => onNavigate(view === "content" ? "media" : "catalogue")}>{view === "content" ? "Open media desk" : "Open product library"}<ArrowUpRight size={17} /></button><button className="button button--outline" onClick={() => onNavigate("overview")}>Back to overview</button></div></section></div>; }

function ProductModal({ product, media, onClose, onSave }: { product: Product | null; media: MediaItem[]; onClose: () => void; onSave: (product: Product) => void }) { const [draft, setDraft] = useState<Product>(product ?? { id: `rnv-${String(Date.now()).slice(-4)}`, name: "", category: "Complexion", price: 0, image: media[0]?.url ?? "", shade: "", stock: 0, status: "Draft", description: "" }); const update = <K extends keyof Product>(key: K, value: Product[K]) => setDraft((current) => ({ ...current, [key]: value })); return <div className="product-modal-wrap" role="dialog" aria-modal="true" aria-label={product ? "Edit product" : "Create product"}><form className="product-modal" onSubmit={(event) => { event.preventDefault(); onSave(draft); }}><div className="modal-top"><div><span className="eyebrow">{product ? "Refine product" : "New shelf piece"}</span><h2>{product ? "Edit product" : "Create product"}</h2></div><button type="button" onClick={onClose} aria-label="Close form"><X size={21} /></button></div><div className="form-grid"><label>Name<input required value={draft.name} onChange={(event) => update("name", event.target.value)} placeholder="Product name" /></label><label>Category<select value={draft.category} onChange={(event) => update("category", event.target.value)}><option>Complexion</option><option>Skin ritual</option><option>Lips</option><option>Sets</option></select></label><label>Price (BDT)<input required min="0" type="number" value={draft.price} onChange={(event) => update("price", Number(event.target.value))} /></label><label>Stock units<input required min="0" type="number" value={draft.stock} onChange={(event) => update("stock", Number(event.target.value))} /></label><label>Shade / size<input value={draft.shade} onChange={(event) => update("shade", event.target.value)} placeholder="e.g. Rose flush" /></label><label>Status<select value={draft.status} onChange={(event) => update("status", event.target.value as ProductStatus)}><option>Draft</option><option>Live</option><option>Low stock</option></select></label><label className="form-full">Description<textarea value={draft.description} onChange={(event) => update("description", event.target.value)} placeholder="A clear product description" /></label><label className="form-full">Product image<select value={draft.image} onChange={(event) => update("image", event.target.value)}>{media.map((item) => <option key={item.id} value={item.url}>{item.name}</option>)}</select></label></div><div className="modal-actions"><button type="button" className="button button--outline" onClick={onClose}>Cancel</button><button className="button button--pink" type="submit"><Check size={17} />Save to release queue</button></div></form></div>; }
