/** Ribbon Modernism cart: a compact paper-and-pink review surface before checkout. */
import { ArrowRight, Minus, Plus, X } from "lucide-react";
import { StoreHeader } from "@/components/StoreHeader";
import { useCart } from "@/contexts/CartContext";
import { trackCart } from "@/lib/analytics";
import { formatBDT } from "@/lib/catalog";
import { useEffect } from "react";

export default function Cart() { const { lines, subtotal, adjust, remove } = useCart(); const delivery = subtotal >= 2000 ? 0 : 150; useEffect(() => { trackCart(lines); }, [lines]); return <div className="site-shell commerce-page"><StoreHeader /><main className="cart-layout"><section><span className="eyebrow">Your bag</span><h1>Chosen with<br /><em>care.</em></h1>{lines.length ? <div className="cart-lines">{lines.map((line) => <article key={line.id}><img src={line.image} alt="" /><div><span>{line.category}</span><h2>{line.name}</h2><p>{formatBDT(line.price)}</p><div className="quantity-control"><button onClick={() => adjust(line.id, -1)} aria-label={`Remove one ${line.name}`}><Minus size={14} /></button><strong>{line.quantity}</strong><button onClick={() => adjust(line.id, 1)} aria-label={`Add one ${line.name}`}><Plus size={14} /></button></div></div><button className="cart-remove" onClick={() => remove(line.id)} aria-label={`Remove ${line.name}`}><X size={18} /></button></article>)}</div> : <div className="empty-commerce"><p>Your bag is waiting for a good ritual.</p><a className="button button--pink" href="/shop">Explore the edit <ArrowRight size={17} /></a></div>}</section>{lines.length > 0 && <aside className="order-summary"><span className="eyebrow">Order summary</span><p><span>Subtotal</span><strong>{formatBDT(subtotal)}</strong></p><p><span>Delivery</span><strong>{delivery === 0 ? "Complimentary" : formatBDT(delivery)}</strong></p><div><span>Total</span><strong>{formatBDT(subtotal + delivery)}</strong></div><small>Free delivery on edits over ৳2,000.</small><a className="button button--ink" href="/checkout">Continue to checkout <ArrowRight size={17} /></a></aside>}</main></div>; }
