/** Ribbon Modernism checkout: deliberate, clear collection of the minimum delivery details required for a protected v2 order and invoice. */
import { ArrowRight, CircleAlert, LockKeyhole } from "lucide-react";
import { useState, type FormEvent } from "react";
import { useLocation } from "wouter";
import { StoreHeader } from "@/components/StoreHeader";
import { useAuth } from "@/contexts/AuthContext";
import { useCart } from "@/contexts/CartContext";
import { createOrder } from "@/lib/api";
import { formatBDT } from "@/lib/catalog";
export default function Checkout() { const { lines, subtotal, clear } = useCart(); const { user } = useAuth(); const [, navigate] = useLocation(); const [name, setName] = useState(user?.name || ""); const [email, setEmail] = useState(user?.email || ""); const [phone, setPhone] = useState(""); const [address, setAddress] = useState(""); const [paymentMethod, setPaymentMethod] = useState<"cod" | "mobile-payment">("cod"); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const delivery = subtotal >= 2000 ? 0 : 150;
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!lines.length) { setError("Your bag is empty."); return; } setSaving(true); setError(""); try { const result = await createOrder({ customerName: name, email, phone, deliveryAddress: address, items: lines.map((line) => ({ id: line.id, quantity: line.quantity })), paymentMethod }); clear(); navigate(result.invoice.url); } catch (cause) { setError(cause instanceof Error ? cause.message : "Checkout could not be completed."); } finally { setSaving(false); } };
  return <div className="site-shell commerce-page"><StoreHeader /><main className="checkout-layout"><section><span className="eyebrow">Checkout</span><h1>One more<br /><em>good decision.</em></h1><form className="checkout-form" onSubmit={submit}><label>Name<input required value={name} onChange={(event) => setName(event.target.value)} /></label><label>Email<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></label><label>Phone<input required value={phone} onChange={(event) => setPhone(event.target.value)} placeholder="01XXXXXXXXX" /></label><label className="form-full">Delivery address<textarea required value={address} onChange={(event) => setAddress(event.target.value)} placeholder="House, road, area, city" /></label><fieldset><legend>Payment</legend><label><input checked={paymentMethod === "cod"} onChange={() => setPaymentMethod("cod")} type="radio" />Cash on delivery</label><label><input checked={paymentMethod === "mobile-payment"} onChange={() => setPaymentMethod("mobile-payment")} type="radio" />Mobile payment</label></fieldset><button className="button button--ink" disabled={saving}>{saving ? "Creating your order" : "Place order & create invoice"}<ArrowRight size={17} /></button>{error && <p className="form-error"><CircleAlert size={16} />{error}</p>}</form></section><aside className="order-summary"><LockKeyhole size={19} /><span className="eyebrow">Protected checkout</span><p><span>{lines.reduce((sum, line) => sum + line.quantity, 0)} items</span><strong>{formatBDT(subtotal)}</strong></p><p><span>Delivery</span><strong>{delivery === 0 ? "Complimentary" : formatBDT(delivery)}</strong></p><div><span>Total</span><strong>{formatBDT(subtotal + delivery)}</strong></div><small>Your order, invoice, and tracking link stay protected by your account or a unique order access link.</small></aside></main></div>; }
