/** Ribbon Modernism order documents: a protected tracking or printable invoice surface that never exposes unrelated customer details. */
import { ArrowLeft, Printer } from "lucide-react";
import { useEffect, useState } from "react";
import { useLocation, useRoute } from "wouter";
import { StoreHeader } from "@/components/StoreHeader";
import { fetchInvoice, fetchOrder, type Order } from "@/lib/api";
import { formatBDT } from "@/lib/catalog";
export default function OrderDocument({ mode }: { mode: "invoice" | "tracking" }) { const [, params] = useRoute(mode === "invoice" ? "/invoice/:id" : "/track/:id"); const [location] = useLocation(); const [order, setOrder] = useState<Order | null>(null); const [error, setError] = useState(""); useEffect(() => { if (!params?.id) return; const access = new URLSearchParams(location.split("?")[1] || "").get("access") || ""; const load = mode === "invoice" ? fetchInvoice(params.id, access).then((data) => data.invoice.order) : fetchOrder(params.id, access).then((data) => data.order); load.then(setOrder).catch((cause) => setError(cause instanceof Error ? cause.message : "This protected order document is unavailable.")); }, [location, mode, params?.id]); return <div className="site-shell commerce-page"><StoreHeader /><main className="document-wrap">{error ? <section className="empty-commerce"><p className="form-error">{error}</p><a className="button button--pink" href="/account">Sign in to your account</a></section> : !order ? <p>Opening your order…</p> : mode === "invoice" ? <Invoice order={order} /> : <Tracking order={order} />}</main></div>; }
function Invoice({ order }: { order: Order }) { return <section className="invoice-paper"><header><div><span className="footer-wordmark">rinova<span>bd</span></span><p>Colour, considered.</p></div><div><span className="eyebrow">Invoice</span><h1>{order.invoiceNumber}</h1><p>Order {order.id}</p></div></header><div className="invoice-meta"><p>Issued<br /><strong>{new Date(order.createdAt).toLocaleDateString("en-BD")}</strong></p><p>Payment<br /><strong>{order.paymentMethod === "cod" ? "Cash on delivery" : "Mobile payment"}</strong></p><p>Status<br /><strong>{order.status}</strong></p></div><table><thead><tr><th>Item</th><th>Qty</th><th>Total</th></tr></thead><tbody>{order.items.map((item) => <tr key={item.id}><td>{item.name}<small>{formatBDT(item.unitPrice)} each</small></td><td>{item.quantity}</td><td>{formatBDT(item.lineTotal)}</td></tr>)}</tbody></table><div className="invoice-total"><p>Subtotal <strong>{formatBDT(order.subtotal)}</strong></p><p>Delivery <strong>{order.delivery === 0 ? "Complimentary" : formatBDT(order.delivery)}</strong></p><h2>Total <strong>{formatBDT(order.total)}</strong></h2></div><footer><a href={`/track/${order.id}${location.search}`}>Track order <ArrowLeft size={16} /></a><button className="button button--ink" onClick={() => window.print()}><Printer size={17} />Print invoice</button></footer></section>; }
function Tracking({ order }: { order: Order }) { return <section className="tracking-card"><a className="back-link" href={`/invoice/${order.id}${location.search}`}><ArrowLeft size={16} />Open invoice</a><span className="eyebrow">Order tracking</span><h1>Your order is<br /><em>{order.status}.</em></h1><p>{order.id} · {order.invoiceNumber}</p><ol>{order.tracking.map((event, index) => <li className={index === order.tracking.length - 1 ? "active" : ""} key={`${event.status}-${event.createdAt}`}><span /><div><strong>{event.status}</strong><p>{event.note}</p><small>{new Date(event.createdAt).toLocaleString("en-BD")}</small></div></li>)}</ol></section>; }
